calc_hits:
- 1
- 3
- 10
check_per_epoch: 10
data_class: KGDataModule
data_path: ../datasets/FB15k-237
dataset_name: FB15K237
decoder_model: ConvE
dropout: 0.5
early_stop_patience: 5
emb_dim: 100
emb_shape: 20
eval_bs: 256
eval_task: link_prediction
fet_drop: 0.2
freq_init: 4
gpu: cuda:1
hid_drop: 0.3
hid_size: 9728
inject_triple_percent: 1.0
inp_drop: 0.2
ipus: null
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_name: CompGCNLitModel
load_config: false
log_every_n_steps: 50
log_gpu_memory: null
logger: true
loss_name: Cross_Entropy_Loss
lr: 0.0001
margin: 12.0
max_epochs: 500
model_name: CompGCN
mu: 10
multiple_trainloader_mode: max_size_cycle
neg_weight: 50
num_batches: 0
num_ent: 14541
num_epoch: 500
num_layers: 2
num_neg: 1
num_nodes: 1
num_processes: 1
num_rel: 474
num_sanity_val_steps: 2
num_workers: 4
opn: corr
optim_name: Adam
out_dim: 200
seed: 321
select_probability: 0.8
shuffle: true
smoothing: 0.1
test_sampler_class: CompGCNTestSampler
train_bs: 1024
train_sampler_class: CompGCNSampler
update_axiom_per: 2
use_wandb: true
use_weight: false
weight_decay: 0.01