adv_temp: 1.0
calc_hits:
- 1
- 3
- 10
check_per_epoch: 10
data_class: KGDataModule
dataset_name: NELL-995
data_path: ../datasets/NELL-995
early_stop_patience: 5
dropout: 0.5
emb_dim: 200
emb_shape: 20
eval_bs: 256
eval_task: link_prediction
filter_flag: true
gpu: cuda:1
litmodel_name: ConvELitModel
loss_name: Cross_Entropy_Loss
lr: 0.001
margin: 12.0
hid_drop: 0.3
hid_size: 9728
inject_triple_percent: 1.0
inp_drop: 0.2
max_epochs: 300
model_name: ConvE
negative_adversarial_sampling: true
num_neg: 256
num_workers: 4
optim_name: Adam
seed: 666
shuffle: true
test_sampler_class: TestSampler
train_bs: 1024
train_sampler_class: ConvSampler
use_wandb: true
use_weight: false
