calc_hits:
- 1
- 3
- 10
check_per_epoch: 5
data_class: KGDataModule
data_path: ../datasets/WN18RR
dataset_name: WN18RR
early_stop_patience: 15
inp_drop: 0.2
hid_drop: 0.3
dropout: 0.2
emb_dim: 128
nheads: 1
nblocks: 1
dim_feedforward: 1024
eval_bs: 256
eval_task: link_prediction
filter_flag: true
litmodel_name: DualAttnELitModel
loss_name: Cross_Entropy_Loss
lr: 0.003
smoothing: 0.1
max_epochs: 500
model_name: DualAttnE
num_neg: 256
gpu: cuda:0
num_workers: 4
optim_name: Adam
seed: 321
shuffle: true
test_sampler_class: TestSampler
train_bs: 512
train_sampler_class: ConvSampler
use_wandb: true
use_weight: false
weight_decay: 0.01