calc_hits:
- 1
- 3
- 10
check_per_epoch: 10
data_class: KGDataModule
data_path: ../datasets/WN18RR
dataset_name: WN18RR
dropout: 0.5
early_stop_patience: 5
emb_dim: 256
nheads: 1
nblocks: 1
dim_feedforward: 1024
eval_bs: 256
eval_task: link_prediction
gpu: cuda:1
litmodel_name: DualAttnELitModel
loss_name: Cross_Entropy_Loss
lr: 0.003
max_epochs: 500
model_name: DualAttnE
multiple_trainloader_mode: max_size_cycle
neg_weight: 10
num_workers: 8
num_neg: 256
negative_adversarial_sampling: true
num_ent: 40943
num_rel: 22
optim_name: Adam
seed: 321
shuffle: true
smoothing: 0.1
test_sampler_class: TestSampler
train_bs: 1024
train_sampler_class: ConvSampler
use_wandb: true
use_weight: false
weight_decay: 0.01