calc_hits:
- 1
- 3
- 10
check_per_epoch: 5
data_class: KGDataModule
data_path: ../datasets/WN18RR
dataset_name: WN18RR
decoder_model: DualAttnE
dis_order: 2
dropout: 0.5
early_stop_patience: 10
emb_dim: 256
eval_bs: 256
eval_task: link_prediction
fet_drop: 0.2
filter_flag: true
freq_init: 4
gpu: cuda:0
hid_drop: 0.3
inject_triple_percent: 1.0
inp_drop: 0.2
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_name: MyCompGCNLitModel
log_every_n_steps: 50
loss_name: Cross_Entropy_Loss
lr: 0.001
max_epochs: 500
model_name: MyCompGCN
nheads: 2
nblocks: 1
dim_feedforward: 1024
mu: 10
multiple_trainloader_mode: max_size_cycle
neg_weight: 50
negative_adversarial_sampling: true
num_batches: 0
num_ent: 40943
num_layers: 2
num_neg: 1
num_rel: 22
num_sanity_val_steps: 2
num_workers: 4
opn: mult
optim_name: Adam
regularization: 0.0
seed: 321
select_probability: 0.8
shuffle: true
slackness_penalty: 0.01
smoothing: 0.1
test_sampler_class: CompGCNTestSampler
track_grad_norm: -1
train_bs: 2048
train_sampler_class: CompGCNSampler
update_axiom_per: 2
use_wandb: true
use_weight: false
val_check_interval: 1.0
weight_decay: 0.01