calc_hits:
- 1
- 3
- 10
check_per_epoch: 5
data_class: KGDataModule
data_path: ../datasets/FB15k-237
dataset_name: FB15K237
decoder_model: ConvE
dropout: 0.5
early_stop_patience: 10
emb_dim: 256
eval_bs: 256
eval_task: link_prediction
fet_drop: 0.2
freq_init: 4
gpu: cuda:0
hid_drop: 0.3
inject_triple_percent: 1.0
inp_drop: 0.2
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_name: MyCompGCNLitModel
loss_name: Cross_Entropy_Loss
lr: 0.0005
max_epochs: 500
model_name: MyCompGCN
nheads: 1
nblocks: 1
dim_feedforward: 1024
mu: 10
multiple_trainloader_mode: max_size_cycle
neg_weight: 50
negative_adversarial_sampling: true
num_batches: 0
num_ent: 14541
num_layers: 2
num_neg: 1
num_rel: 474
num_workers: 4
opn: corr
optim_name: Adam
seed: 321
select_probability: 0.8
shuffle: true
slackness_penalty: 0.01
smoothing: 0.1
test_sampler_class: CompGCNTestSampler
train_bs: 2048
train_sampler_class: CompGCNSampler
use_wandb: true
use_weight: false
weight_decay: 0.01
