calc_hits:
- 1
- 3
- 10
check_per_epoch: 5
data_class: KGDataModule
data_path: ../datasets/FB15k-237
dataset_name: FB15K237
early_stop_patience: 10
emb_dim: 256
nheads: 2
nblocks: 1
dim_feedforward: 1024
eval_bs: 256
eval_task: link_prediction
filter_flag: true
litmodel_name: DualAttnELitModel
loss_name: Cross_Entropy_Loss
lr: 0.005
smoothing: 0.1
max_epochs: 500
num_ent: 14541
num_rel: 474
model_name: DualAttnE
num_neg: 512
gpu: cuda:1
num_workers: 8
optim_name: Adam
seed: 666
shuffle: true
test_sampler_class: TestSampler
train_bs: 2048
train_sampler_class: ConvSampler
use_wandb: true
use_weight: false
