calc_hits:
- 1
- 3
- 10
check_per_epoch: 5
data_class: KGDataModule
data_path: ../dataset/WN18RR
dataset_name: WN18RR
early_stop_patience: 5
emb_dim1: 256
emb_dim2: 256
nheads: 2
nblocks: 1
dim_feedforward: 1024
eval_bs: 256
attn_type: dual
eval_task: link_prediction
filter_flag: true
gpu: cuda:0
litmodel_name: CTELitModel
loss_name: Cross_Entropy_Loss
lr: 0.001
margin: 9.0
max_epochs: 100
model_name: CTE
num_neg: 256
num_workers: 8
optim_name: Adam
seed: 666
shuffle: true
test_sampler_class: TestSampler
train_bs: 1024
train_sampler_class: ConvSampler
use_wandb: true
use_weight: false
