adv_temp: 1.0
calc_hits:
- 1
- 3
- 10
check_per_epoch: 5
data_class: KGDataModule
dataset_name: FB15K237
data_path: ../dataset/FB15K237
early_stop_patience: 3
emb_dim: 200
eval_bs: 256
eval_task: link_prediction
filter_flag: true
gpu: cuda:0
litmodel_name: ConvELitModel
loss_name: Cross_Entropy_Loss
lr: 0.0005
margin: 9.0
max_epochs: 100
model_name: ConvE
negative_adversarial_sampling: true
num_neg: 256
num_workers: 8
optim_name: Adam
seed: 666
shuffle: true
test_sampler_class: TestSampler
train_bs: 1024
train_sampler_class: ConvSampler
use_wandb: true
use_weight: false
