calc_hits:
- 1
- 3
- 10
check_per_epoch: 5
data_class: KGDataModule
data_path: ../datasets/FB15k-237
dataset_name: FB15K237
decoder_model: ConvE
dropout: 0.5
early_stop_patience: 5
emb_dim: 100
emb_shape: 20
eval_bs: 256
eval_task: link_prediction
fet_drop: 0.2
freq_init: 4
gpu: cuda:0
hid_drop: 0.3
hid_size: 9728
inject_triple_percent: 1.0
inp_drop: 0.2
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_name: CompGCNLitModel
log_every_n_steps: 50
logger: true
loss_name: Cross_Entropy_Loss
lr: 0.0001
margin: 12.0
max_entialments: 2000
max_epochs: 300
model_name: CompGCN
move_metrics_to_cpu: false
mu: 10
multiple_trainloader_mode: max_size_cycle
neg_weight: 50
negative_adversarial_sampling: true
norm_flag: false
num_batches: 0
num_ent: 14541
num_epoch: 300
num_layers: 2
num_neg: 1
num_rel: 474
num_workers: 8
opn: mult
optim_name: Adam
out_dim: 200
process_position: 0
regularization: 0.0
seed: 666
select_probability: 0.8
shuffle: true
slackness_penalty: 0.01
smoothing: 0.1
test_sampler_class: CompGCNTestSampler
train_bs: 2048
train_sampler_class: CompGCNSampler
use_wandb: true
use_weight: false
weight_decay: 0.01
