calc_hits:
- 1
- 3
- 10
check_per_epoch: 10
data_class: KGDataModule
data_path: ../datasets/NELL-995
dataset_name: NELL-995
dis_order: 2
dropout: 0.5
early_stop_patience: 10
emb_dim: 500
eval_bs: 16
eval_task: link_prediction
fet_drop: 0.2
gpu: cuda:1
hid_drop: 0.3
inp_drop: 0.2
litmodel_name: KGELitModel
loss_name: Adv_Loss
lr: 0.0001
margin: 9.0
max_epochs: 500
model_name: RotatE
multiple_trainloader_mode: max_size_cycle
neg_weight: 50
negative_adversarial_sampling: true
num_workers: 4
optim_name: Adam
out_dim: 200
seed: 321
shuffle: true
smoothing: 0.1
test_sampler_class: TestSampler
train_bs: 512
train_sampler_class: UniSampler
use_wandb: true
use_weight: false
weight_decay: 0.01