calc_hits:
- 1
- 3
- 10
check_per_epoch: 10
data_class: KGDataModule
data_path: ../datasets/WN18RR
dataset_name: WN18RR
dis_order: 2
dropout: 0.5
early_stop_patience: 10
emb_dim: 500
eval_bs: 16
eval_task: link_prediction
fet_drop: 0.2
gpu: cuda:1
hid_drop: 0.3
hid_size: 9728
inp_drop: 0.2
litmodel_name: KGELitModel
loss_name: Adv_Loss
lr: 1.0e-06
margin: 6.0
max_epochs: 500
model_name: RotatE
mu: 10
multiple_trainloader_mode: max_size_cycle
neg_weight: 50
negative_adversarial_sampling: true
num_ent: 40943
num_epoch: 500
num_layers: 2
num_neg: 512
num_rel: 11
num_workers: 4
optim_name: Adam
out_dim: 200
seed: 666
shuffle: true
smoothing: 0.1
test_sampler_class: TestSampler
train_bs: 512
train_sampler_class: UniSampler
update_axiom_per: 2
use_wandb: true
use_weight: false
val_check_interval: 1.0
weight_decay: 0.01
weights_summary: top